### DISCUSSION TITLE
Request - Absolute idiots guide for installation

### DISCUSSION THREAD

**Discussion by boxgr0ve** [0x2142/frigate-notify#198] [Q&A] [answered]
I'm struggling to understand how to install and configure.  Firstly I tried using portainer as I had it installed on my proxmox server (which also runs hass.io where frigate is installed) I set these up a couple of years ago and now cannot remember the process. 

After a while I managed to get the image uploaded and a container created but when I try running it I get an error " Stopped for a few seconds with exit code 1" presumably because I have not created a config file, but I cannot see where to add one. 

Next I installed the docker macOS app and again I managed to get the image loaded but when trying to run I get the following error. 

2025-02-01 15:13:03 2025/02/01 15:13:03 +0000 INF Frigate Notify - v0.4.0
2025-02-01 15:13:03 2025/02/01 15:13:03 +0000 INF Starting...
2025-02-01 15:13:03 2025/02/01 15:13:03 +0000 WRN Config file could not be read, attempting to load config from environment
2025-02-01 15:13:03 2025/02/01 15:13:03 +0000 FTL Failed to load config from environment! error="alerts: required validation failed, frigate: required validation failed"

My clue is I need to link the container to a 'volume' but I can't see easily how to do it...

I've never really used docker before so the process is unfamiliar to me.

Is it possible for a quick video work through with an initial configuration.  if I can see how someone does it, I should be able to work it out myself.  Many thanks.

**Comment by boxgr0ve** [comment]
Right I've done a bit more learning and realised that portainer is a front end for Docker... Not sure if I'm on the right path here, but I've created a volume through portainer called 'frigate'

the mount path is: /var/lib/docker/volumes/frigate/_data

I've then used 'stacks' in portainer and pasted in the docker-compose.yml file....

```
version: "3.0"
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:latest
    # Uncomment below if REST API server is enabled
    # ports:
    #   - "8000:8000"
    environment:
      - TZ=Etc/UTC
    volumes:
      - /path/to/config.yml:/app/config.yml
    restart: unless-stopped
```

I know the volumes path is incorrect above... can someone please advise what I need to put?  I also can't find a way to actually add files to the volume..... please help!
