### DISCUSSION TITLE
Docker env problem

### DISCUSSION THREAD

**Discussion by kinouzero** [0x2142/frigate-notify#212] [Q&A]
Hi everyone,

I tried to setup this project with this compose, I prefer using env to avoid mapping config file :

```yaml
frigate-notify:
    <<: [*basic, *extra-hosts, *network-zero, *restart-always]
    container_name: ${FRIGATE_NOTIFY_NAME}
    environment:
      FN_DEBUG: ${TRUE}
      FN_LOGLEVEL: ${LOG_LEVEL}
      FN_FRIGATE_SERVER: ${FRIGATE_URL}
      FN_FRIGATE_IGNORESSL: ${TRUE}
      FN_FRIGATE_PUBLIC_URL: ${NVR_URL}
      FN_MQTT_ENABLED: ${TRUE}
      FN_MQTT_SERVER: ${HASS_HOST}
      FN_ALERTS_NTFY_ENABLED: ${TRUE}
      FN_ALERTS_NTFY_IGNORESSL: ${TRUE}
      FN_ALERTS_NTFY_SERVER: ${NTFY_HOST}
      FN_ALERTS_NTFY_TEMPLATE: ${FRIGATE_NOTIFY_NTFY_TEMPLATE}
      FN_ALERTS_NTFY_TOPIC: ${FRIGATE_NAME}
      TZ: ${TZ}
    image: ghcr.io/0x2142/frigate-notify:latest
    labels:
      <<: *label-wud-latest
      wud.display.icon: 'sh-frigate'
      wud.display.name: 'Frigate Notify'
      wud.link.template: 'https://hub.docker.com/r/antlafarge/jdownloader/tags'
    pull_policy: always
```

I have this error :

```bash
INF main.go:96 > Frigate Notify - v0.4.2
INF main.go:97 > Starting...
DBG config/config.go:39 > Attempting to load config file: ./config.yml
WRN config/config.go:44 > Config file could not be read, attempting to load config from environment
FTL config/config.go:49 > Failed to load config from environment! error="alerts: required validation failed, frigate: required validation failed"
```

 I tried to check the code but the only required env is frigate server and all env have the correct values :
```json
Env:[
"FN_ALERTS_NTFY_TOPIC=frigate",
"FN_FRIGATE_SERVER=http://frigate:5000",
"FN_FRIGATE_IGNORESSL=true",
"TZ=Europe/Paris",
"FN_ALERTS_NTFY_SERVER=http://ntfy",
"FN_FRIGATE_PUBLIC_URL=https://nvr.***",
"FN_ALERTS_NTFY_ENABLED=true",
"FN_MQTT_SERVER=hass.local",
"FN_ALERTS_NTFY_IGNORESSL=true",
"FN_ALERTS_NTFY_TEMPLATE=Looks like {{ .Camera }} spotted a {{ .Label }}!!",
"FN_MQTT_ENABLED=true",
"FN_LOGLEVEL=debug",
"FN_DEBUG=true",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
],
```

Can someone help me on this matter ?
