### ISSUE TITLE
Improvement: Allow Golang templates for notifier headers

### ISSUE THREAD

**Issue by freefd** [0x2142/frigate-notify#100]
Allow to use Golang template engine for notification headers, as it is already used for the notification body.
Mostly useful for Webhook notifier.

Also, when implemented, the hard-coded [X-Actions header for Ntfy](https://github.com/0x2142/frigate-notify/blob/main/notifier/nfty.go#L46) can be moved to default Ntfy configuration.

**Comment by 0x2142** [comment]
Sounds good. I'll add it to the backlog 👍

**Comment by freefd** [comment]
Sample usage for Ntfy:

```yaml
    headers:
      - Authorization: Basic {{ env.Getenv "FN_NTFY_AUTH_BASIC" }}
      - X-Priority: "{{ if ge (len .Zones ) 1 }} 4{{ else }} 3{{ end }}"
      - X-Tags: "{{ if ge (len .Zones ) 1 }} rotating_light, {{ end }}walking"
```

Produces a message with normal (3) severity when the object is in the camera FOV but out of any zone:
![image](https://github.com/user-attachments/assets/d76d8b28-ebcc-422a-9b02-5fabe4d9664a)

And produces a message with high (4) priority when the object crossed the zone:
![image](https://github.com/user-attachments/assets/aaf4f43e-8bec-4577-a5a4-f66d6d9e4e06)

The Ntfy app is configured to only alert on messages of high severity and to keep a silent on messages with normal severity, so as not to bother the user too often.
