### ISSUE TITLE
Infrequent notifications

### ISSUE THREAD

**Issue by mjalindahl** [0x2142/frigate-notify#108]
Hi there,

Mostly loving this utility so far, definitely like not having to use HA for the notifications.

Anyway - I hardly ever receive notifications when there's cars or people.  Dogs seem to work pretty much all the time.

Is this related to the /review project on Frigate v14?  Is there anything I can do in the meantime so I get all notifications?

Thanks.

**Comment by mjalindahl** [comment]
Bump. Any thoughts?

**Comment by 0x2142** [comment]
Hey there - Sorry about the delay. I had to step away for a little bit for personal reasons, but I'm back now & starting to catch up on things.

Could you share the config you're using? And if possible, it would be helpful to enable [debug logging](https://frigate-notify.0x2142.com/latest/config/options/) and capture an instance where cars or people were detected but you didn't get a notification.

Thanks!

**Comment by mjalindahl** [comment]
Here's my config:

```
frigate:
  server: http://192.168.1.189:5000
  ignoressl: true
  public_url: https://my.domain.tld
#  headers:
  startup_check:
    attempts: 3
    interval: 5

  webapi:
    enabled: true
    interval: 3

  mqtt:
    enabled: false
    server: 192.168.1.3
    port: 1883
#    clientid:
    username: mqtt
    password: mqtt
    topic_prefix: frigate

#  cameras:
#    exclude:
#      - test_cam_01

alerts:
  general:
    title: My Title
#    timeformat:
    nosnap:

  zones:
    unzoned: allow
    allow:
#     - test_zone_01
    block:
#     - test_zone_02

#  labels:
#    allow:
#     - car
#     - person
#     - dog
#    block:
#     - bird
```

I took a look at the Docker logs, and 99/100 times when there's a car, I get this in the logs:

`2024/08/05 17:40:03 +0000 INF New event received event_id=1722879603.015435-yas3zp
2024/08/05 17:40:03 +0000 INF Event Detected camera=BackDoor event_id=1722879603.015435-yas3zp label=car zones=
2024/08/05 17:40:03 +0000 INF Event dropped - No snapshot or clip available event_id=1722879603.015435-yas3zp`

My Frigate instance is running on the same box, it hovers around 20% CPU, I've tried via MQTT and the API, and I still seem to be seeing this error whenever a car or person shows up, and I don't get alerted.  I'm on the latest v0.3.2, I've tried `nosnap: allow` and commenting it out (to use the defaults).

Frigate itself shows the cars just fine, I'm just not getting alerted.

Thanks for the help.
