### ISSUE TITLE
Unable to get notifications on telegram

### ISSUE THREAD

**Issue by ronzino83** [0x2142/frigate-notify#132]
I am having difficulties to bring notifications on telegram. 

Log does not report telegram releted issues,and correctly report event on motion detection

I have created a telegram bot,got the id and chat id,but notifications does not come.

My config.yml follows

Do i have to setup something more on the bot ? Always used bots but it is the first time i create one

```yaml
frigate:
  server: http://192.168.119.33:5000
  ignoressl: true

  webapi:
    enabled: true                                                    
    interval: 30

  mqtt:
    enabled: false                                               
  cameras:
    exlude:                                                      
  alerts:                                                         
   general:
      title: Frigate Alert
      timeformat: Mon, 02 Jan 2006 15:04:05 MST
      nosnap: allow
      snap_bbox: false
      snap_timestamp: false
      snap_crop: false

    quiet:
      start:
      end:
                        
    zones:
      unzoned: allow
      allow:
      block:

    labels:
      min_score: 30
      allow:
      block:

    telegram:
      enabled: true
      chatid: 11xxxx
      token: 69xxxxx
      template:

  monitor:
    enabled: false
    url:
    interval:
    ignoressl:
```
