### ISSUE TITLE
notifications doesn't work, what I am doing wrong.

### ISSUE THREAD

**Issue by Mareckil** [0x2142/frigate-notify#134]
Hello, I am trying to set up notifications from my frigate 0.14.1. I did try smtp and now I  am trying discord none of them worked at all

```yaml
frigate:
  server: https://192.168.1.160:8971
  ignoressl: true
  public_url:
  headers:
  startup_check:
    attempts:
    interval:

  mqtt:
    enabled: true
    server: 192.168.1.160
    port: 1883
    clientid: frigate_notify
    username: xxxxx
    password: xxxxx
    topic_prefix: frigate_1

alerts:
  general:
    title: Frigate Alert
    timeformat: Mon, 02 Jan 2006 15:04:05 MST
    nosnap:
    snap_bbox: true
    snap_timestamp: true
    snap_crop:


  zones:
    unzoned: allow
    allow:
    block:

  labels:
    allow:
     - person
     - car
    block:

  smtp:
    enabled: false
    server: smtp.op.tld
    port: 465
    tls: true
    user: xxxxxx@op.tld
    password: xxxxxxxxxxx
    recipient: xxxxxx@op.tld
    template: "Looks like {{ .Camera }} spotted a {{ .Label }}!!"

  discord:
    enabled: true
    webhook: https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    template: "Looks like {{ .Camera }} spotted a {{ .Label }}!!"
```
