### ISSUE TITLE
Notifications not working. 

### ISSUE THREAD

**Issue by Mareckil** [0x2142/frigate-notify#135]
I am trying to setup notifications, unfortunately without success. My frigate is connecting to mqtt broker like that:

```yaml
 mqtt:
  enabled: true
  host: 192.168.1.160
  port: 1883
  user: mosquitto
  password: passwd
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
```

frigate-notify:

```yaml
  mqtt:
    enabled: true
    server: 192.168.1.160
    port: 1883
    clientid: frigate_notify
    username: mosquitto
    password: passwd
    topic_prefix: frigate/events
```

Is it right or not?
