### ISSUE TITLE
still problem with notifications

### ISSUE THREAD

**Issue by Mareckil** [0x2142/frigate-notify#139]
Installed dev version and changed to ntfy.sh
and getting this error:

```text
WRN HTTP Request failed, retrying in 10 seconds... error="Post \"ntfy.sh/rafvesyunudert167\": unsupported protocol scheme \"\"" attempt=1 max_tries=6
```

What am I doing wrong

```yaml
frigate:
  server: https://192.168.1.160:8971
  ignoressl: true
  public_url:
  headers:
  startup_check:
    attempts:
    interval:

  mqtt:
    enabled: true
    server: 192.168.1.160
    port: 1883
    clientid: frigate_notify
    username: mosquitto
    password: passwd
    topic_prefix: frigate

 # cameras:
 #   exclude:
 #     - cam1
 #     - cam2

alerts:
  general:
    title: Frigate
    timeformat: Mon, 02 Jan 2006 15:04:05 MST
    nosnap:
    snap_bbox: true
    snap_timestamp: true
    snap_crop:


  zones:
    unzoned: allow
    allow:
    block:

  labels:
    allow:
     - person
     - car
    block:

  smtp:
    enabled: false
    server: smtp.poczta.onet.pl
    port: 465
    tls: true
    user: user@op.pl
    password: FRZZ-HIWV-70H
    recipient: user@op.pl
    template: "Looks like {{ .Camera }} spotted a {{ .Label }}!!"

  discord:
    enabled: false
    webhook: https://discord.com/api/webhooks/1287448703782617238/YcY5lPL3kzJDi1k2RYwr2oOmUGzcCd-S-E8AHz58ufyAFzS2M?thread_name=RafalFrigate
    template: "Looks like {{ .Camera }} spotted a {{ .Label }}!!"

  ntfy:
    enabled: True
    server: ntfy.sh
    topic: rafvesyunudert167
    ignoressl:
    headers:
    template:
```
