### ISSUE TITLE
[API/Alerts] top_score not parsed correctly?

### ISSUE THREAD

**Issue by SHU-red** [0x2142/frigate-notify#161]
**Describe the bug**
- Yesterday i made use of your awesome and cleanly documented project &rarr; Thanks for that 🙏 
- Everything is up and my telegram notifications are working
- I wanted to use the alerts - labels - min_score setting to only get notified above a certain score
- I did set it to 75 and did not get any notification anymore, despite having many events with higher score than 75
- In the telegram message text (which i did not change from default) is the correct label & score

I checked my /api/events endpoint and got (which shows a top-level top_score of "null", within the data section the correct score is shown
```yaml
[
  {
    "box": null,
    "camera": "garage",
    "data":
      {
        "attributes": [],
        "box":
          [
            0.428125,
            0.1425925925925926,
            0.37864583333333335,
            0.8527777777777777,
          ],
        "region":
          [0.3104166666666667, 0.0, 0.6145833333333334, 1.0925925925925926],
        "score": 0.9731574058532715,
        "top_score": 0.9655845165252686,
        "type": "object",
      },
    "end_time": 1730320228.789495,
    "false_positive": null,
    "has_clip": true,
    "has_snapshot": true,
    "id": "1730320212.849335-3ck4p9",
    "label": "person",
    "plus_id": null,
    "retain_indefinitely": false,
    "start_time": 1730320207.849335,
    "sub_label": null,
    "thumbnail": "nonono",
    "top_score": null,
    "zones": [],
  },
]

```

- I already read #54 which seems to be linked to this but does not mess with min_score
- I already made sure at frigate that the top_score on top-level is deprecated: https://github.com/blakeblackshear/frigate/discussions/14696

**Expected behavior**
- After setting min_score to 75 i shall still get notifications but only for images containing objects with higher score of 75

**To Reproduce**

**Versions:**
 - Frigate NVR: 0.14.1-f4f3cfa
 - Frigate-Notify: 0.3.5

**Frigate-Notify Config:**
```yaml
alerts:
  labels:
    min_score: 75
```

**Additional context**
- Everything above is just guessed
- If im wrong i can try to dig more deep into my specific problem but it feels like the (?lately?) done changed in frigate-api could lead to this inconsistency
- BTW: Is there a way to set a score per label?
