### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by jbriscoenc** [0x2142/frigate-notify#172]
Having an issue getting eastern standard time showing...  What am I doing wrong?

```yaml
## Alerting methods
# Any combination of alert destinations can be configured
alerts:
  # General config applies to all alert methods below
  general:
    # Title for any alert messages (Default: Frigate Alert)
    # Supports template variables
    title: Camera Alert
    # Optionally modify default time format in notifications
    # Use Golang's reference time format, or see docs for more info
    timeformat: Mon, 02 Jan 2006 15:04:05 EST
    # Allow notification of events without a snapshot
    # Set to `drop` to disallow this
    nosnap: allow
    # Note: Following snap_ items only apply when event is in progress
    # Set to `true` to include bounding box on detected object in snapshot
    snap_bbox: true
    # Set to `true` to include timestamp on snapshot
    snap_timestamp: true
    # Set to `true` to crop snapshot
    snap_crop:
```
