### ISSUE TITLE
alerts: required validation failed

### ISSUE THREAD

**Issue by mauricio-camayo** [0x2142/frigate-notify#184]
I'm having the same issue you solved here:

```
              Hello there & thanks for using this app! 

   So the key here is the log that states `WRN Config file could not be read`. The default location for the config file is `/app/config.yml`, or it can be overriden by using the `FN_CONFIGFILE` environment variable as shown [here](https://frigate-notify.0x2142.com/latest/install/#docker-recommended).

In the config shared, it looks like you're mounting the config to `/app/config/config.yml` - so my best guess is that the app can't find it. I would suggest either updating the volume map to `/app/config.yml`, or use the env var if you like!

Edit: I see the docs might be a little confusing on the default file location - I'll make a note to update this to clarify it


_Originally posted by @0x2142 in https://github.com/0x2142/frigate-notify/issues/156#issuecomment-2408710154_
```

Except I do not have the WRN message.

**Comment by mauricio-camayo** [comment]
This is the exact error I'm having:
```
2024/12/29 01:48:46 +0000 INF Frigate Notify - v0.3.5
2024/12/29 01:48:46 +0000 INF Starting...
2024/12/29 01:48:46 +0000 FTL Failed to load config from file! error="alerts: required validation failed"
```
here's my compose file

```
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:latest
    environment:
      - TZ= Etc/UTC
    volumes:
      - /srv/dev-disk-by-uuid-aa949b97-12b8-48c8-b6a4-e09a65bc3e34/frigate-notify/config.yml:/app/config.yml
    restart: unless-stopped
```
I have double check the permissions and even run from the console using:
`sudo docker run -v /srv/dev-disk-by-uuid-aa949b97-12b8-48c8-b6a4-e09a65bc3e34/frigate-notify/config/config.yml:/app/config.yml ghcr.io/0x2142/frigate-notify:latest`
Still cannot see the error on my config
