### ISSUE TITLE
Event dropped - Already notified on this zone

### ISSUE THREAD

**Issue by stinkyplant** [0x2142/frigate-notify#190]
Using the dev branch with app mode reviews I'm trying to get notified for sub labels. e.g., fedex or usps. Watching the logs I see the proper detection, but I don't get notified it either says "Event dropped - Already notified on this zone" or event dropped by filter (I don't notify for car). 

I'm using the filter for different notifications so I can get car notifications in the driveway zone. 

"rocessing review... camera=Driveway num_detections=1 objects=fedex review_id=1736196668.81419-v22ib7 severity=alert zones=mail"

My config filter for second instant of pushover. 

filters:
        zones:
        # - mail
       # cameras:
        # - Driveway
        sublabels:
         - usps
         - fedex
         - ups
   
  I don't have any blocks in the global config everything is filtered in the pushover config(s) for person and zones. Unzoned is allowed. Other notifications work properly. Is it because I don't have "car" as a label? I don't want to be notified of all cars. 

Full Config

```
app:
 mode: reviews

frigate:
  server: http://ip
  ignoressl:
  public_url:
  headers:
  startup_check:
    attempts:
    interval:

  webapi:
    enabled: false
    interval: 
 
  mqtt: 
    enabled: true
    server: ip
    port:
    clientid:
    username: user
    password: pass
    topic_prefix: 

  cameras:
    exclude:
      - test_cam_01

alerts:  
  general:
    title:
    timeformat:
    nosnap:
    snap_bbox: true
    snap_timestamp:
    snap_crop:
    notify_once: 
    notify_detections: true
  quiet:
    start:
    end:

  zones:
    unzoned: allow 
    allow:
    # - dw_car
    # - dw_yard
    # - dw_street
    # - db_yard
    # - db_street
    # - fy_yard
    # - fy_street
    # - by_yard
    # - porch
    # - mail
    block:
    # - fy_street
    # - dw_street

  labels:
    min_score: 50 
    allow:
    # - person
    # - dog
    # - cat
    # - car
    # - bird
    # - usps
    # - fedex
    # - ups
    # - package
    # - speech
    block:
    # - car

  sublabels:
 #   allow:
  #   - usps
   # block:
    # - EFGH

  discord:
    enabled: false
    webhook: 
    template:

  gotify:
    enabled: false
    server:
    token: 
    ignoressl:
    template:

  smtp:
    enabled: false
    server: 
    port: 
    tls: 
    user:
    password:
    recipient:
    template:

  telegram:
    enabled: false
    chatid:
    token:
    template:

  pushover:
    - enabled: true
      token: token
      userkey: key
      devices:
      priority:
      retry:
      expire:
      ttl:
      template:
      sound: gamelan
      filters:
       zones:
       # - db_yard
       # - db_street
       # - fy_yard
       # - fy_street
       # - by_yard
       # - porch
       # - dw_yard 
       # - dw_street
       labels:
        - person
        - speech
        - package       
    - enabled: true
      token: token
      userkey: key
      devices:
      priority:
      retry:
      expire:
      ttl:
      template:
      sound: bike
      filters:
       zones: 
        - dw_car
       labels:
        - car
       # - person 
    - enabled: true
      token: token
      userkey: key
      devices:
      priority:
      retry:
      expire:
      ttl:
      template:
      sound: bugle
      filters:
        zones: 
        # - mail
       # cameras:
        # - Driveway
        sublabels:
         - usps
         - fedex
         - ups
 ```
