### ISSUE TITLE
Bad Request: IMAGE_PROCESS_FAILED

### ISSUE THREAD

**Issue by boxgr0ve** [0x2142/frigate-notify#208]
Getting the following error - I'm afraid I'm not sure where to start with debugging.

I can confirm my telegram bot works fine and receives messages using different services but I get nothing on this. 

`25/02/07 07:50:00 +0000 INF New event received event_id=1738914600.326151-nnaigv
2025/02/07 07:50:00 +0000 INF Processing event... camera=doorbell_camera event_id=1738914600.326151-nnaigv label=person zones=
2025/02/07 07:50:00 +0000 INF Event dropped - No snapshot or clip available event_id=1738914600.326151-nnaigv
2025/02/07 07:50:00 +0000 INF Event update received event_id=1738914600.326151-nnaigv
2025/02/07 07:50:00 +0000 INF Processing event... camera=doorbell_camera event_id=1738914600.326151-nnaigv label=person zones=
2025/02/07 07:50:01 +0000 WRN Unable to send alert error="Bad Request: IMAGE_PROCESS_FAILED" event_id=1738914600.326151-nnaigv provider=Telegram provider_id=0
2025/02/07 07:50:01 +0000 INF Event update received event_id=1738914600.326151-nnaigv
2025/02/07 07:50:01 +0000 INF Processing event... camera=doorbell_camera event_id=1738914600.326151-nnaigv label=person zones=driveway,full_area
2025/02/07 07:50:01 +0000 WRN Unable to send alert error="Bad Request: IMAGE_PROCESS_FAILED" event_id=1738914600.326151-nnaigv provider=Telegram provider_id=0`

Frigate is running on home assistant - 0.14.1-f4f3cfa
frigate notify v0.4.0

Here is my config - it can probably be shrunk down but I'm still learning. 

```
app:
  mode: events
  api:
    enabled:
    port:

frigate:

  server: http://192.168.1.251:8123/ccab4aaf_frigate/ingress
  ignoressl: true
  public_url:

  headers:

  startup_check:
    attempts: 3
    interval: 30

  mqtt: 
    enabled: true
    server: 192.168.1.251
    port:
    clientid:
    username: [SECRET]
    password: [SECRET]
    topic_prefix: 
  
  cameras:
    exclude:
      - test_cam_01

alerts:  
  general:
    title:
    timeformat:
    nosnap: allow
    snap_bbox:
    snap_timestamp:
    snap_crop:
    notify_once:
    notify_detections:
    recheck_delay:
    audio_only: allow

  quiet:
    start:
    end:

  zones:
    unzoned: allow
    allow:
     - driveway
    block:
     - test_zone_02

  labels:
    min_score:
    allow:
    block:

  sublabels:
    allow:
    block:

  telegram:
    enabled: true
    chatid: [SECRET]
    token: [SECRET]
    template:
```
