### ISSUE TITLE
Error 401 trying to access through port 8971

### ISSUE THREAD

**Issue by IkerGarcia** [0x2142/frigate-notify#213]
While it has been working succesfully through port 5000, I moved to 8971 with authentication. I get always error 401, I tried several headers and also a simple password. 

```
frigate:
  server: http://IP:8971
  ignoressl:
  public_url:
  headers:
      - Authorization: username simplepass
  startup_check:
    attempts:
    interval:
```
Other services, like HAOS integration, work. Thank you.
