### ISSUE TITLE
Pushover - multiple sounds

### ISSUE THREAD

**Issue by mjalindahl** [0x2142/frigate-notify#214]
Hi again,

I think this is already an option, but I don't remember.

Is doing multiple sounds for Pushover available now?  i.e. dog=bark, person=whatever, car=carhorn, etc.?  I seem to recall that being a thing, but I can't seem to find any documentation on it.

Thanks!

**Comment by 0x2142** [comment]
Hi there - Yes this should be possible now that you can create multiple profiles per alert provider. So each profile is an instance of the Pushover alert config, and you could specify a filter for each with a different sound.

For example:

```yaml
  pushover:
    - enabled: true
      token: 
      userkey: 
      sound: bark
      filters:
        labels:
          - dog
    - enabled: true
      token: 
      userkey: 
      sound: pianobar
      filters:
        labels:
          - person
    - enabled: true
      token: 
      userkey: 
      sound: carhorn
      filters:
        labels:
          - car
```
