### ISSUE TITLE
SOME text

### ISSUE THREAD

**Issue by itunit111** [0x2142/frigate-notify#226]

**Comment by 0x2142** [comment]
Hi there - Can you share a copy of your frigate-notify config? And is frigate-notify set to the correct time zone? 

Currently there is no way to set quiet periods for certain days of the week - only time ranges within each day.

**Comment by itunit111** [comment]
Hello. Thanks for the answer. I don't post the app: and frigate: sections because... They're fine.

# Alerting methods
alerts:
  general:
    title: "some text"
    timeformat: "2006-01-02 15:04:05"  
    nosnap: allow  
    snap_crop: false
    snap_bbox: true  
    snap_timestamp: false  
    max_snap_retry: 10  
    notify_once: true  
    notify_detections: true  
    recheck_delay: 0  
    audio_only: drop  
  
#  zones:
#    unzoned: drop  
#    allow:
#      - Enter  
#      - Space
#      - Registration     
#    block: []  

 #  quiet:
#    start: "23:00"  
#    end: "07:00"  

  enter_zone_alert:
    zones:
      - Enter  
    filters:
      labels:
        - person  
    quiet:
      start: "06:00"  
      end: "23:00"    
#    template: "some text"
    
  space_zone_alert:
    zones:
      - Space  
    filters:
      labels:
        - person  
    quiet:
      start: "07:00"  
      end: "21:00"    
#    template: "some text"
    
  registration_zone_alert:
    zones:
      - Registration  
    filters:
      labels:
        - person  
    quiet:
      start: "08:00"  
      end: "18:00"    
    template: "some text"

  labels:
    min_score: 0  
    allow:
      - person  
    block: []     

  telegram:
    enabled: true  
    token: "some token"  
    chatid: "some cahtid"  
    template: "some text"
    send_snapshot: true

**Comment by 0x2142** [comment]
Thanks for sharing the config - that helps a lot. So the configuration for multiple Telegram profiles is not quite correct.

Using your config, here's an example of how that would be configured:

```yaml
telegram:
  - enabled: true
    token: some token
    chatid: some cahtid
    template: some text
    filters:
      zones:
        - Enter
      filters:
        labels:
          - person
      quiet:
        start: 06:00
        end: 23:00
  - enabled: true
    token: some token
    chatid: some cahtid
    template: some text
    filters:
      zones:
        - Space
      filters:
        labels:
          - person
      quiet:
        start: 07:00
        end: 21:00
  - enabled: true
    token: some token
    chatid: some cahtid
    template: some text
    filters:
      zones:
        - Registration
      filters:
        labels:
          - person
      quiet:
        start: 08:00
        end: 18:00
      template: some text
```

Can you please try to update your configuration to be similar & try again?
