### ISSUE TITLE
Error Code 400 with Ntfy and Frigate Web API

### ISSUE THREAD

**Issue by al70023** [0x2142/frigate-notify#227]
No matter what I try, I get error 400 codes when using the ntfy integration. 

I've enabled the frigate-notify api, and when sending /api/v1/notif_test API requests, I get back a 202 accepted response, however my frigate-notify container logs show:

![Image](https://github.com/user-attachments/assets/825968fe-c792-4cf2-8b9b-cf6355e38e75)

Additionally, when setting up my config file, I've tried all sorts of combinations of my Ntfy server URL and topic and headers, but am not able to get a notification sent to it. I get the same error code.

If I change my address to the http://[ip-address] or I use https://[url] I get the same 400 error code. If I purposely input an incorrect ip address or incorrect url where my Ntfy container is running, then frigate-notify correctly shows an error that the route is wrong and it cannot find that location. So I see that I only have the error 400 code when I have the correct address of my Ntfy host. 

However, I've observed that no matter what I change the topic name to, whether it is the correct one or one that doesn't exist, I get the same 400 code.

Lastly, I can curl a message directly to my Ntfy server and the message will instantly appear, so it seems that only frigate-notify is unable to send a notification to it from the config file or however it is set up. Here is my config file, please let me know if I am missing a critical step:

```
app:
  mode: reviews
  api:
    enabled: true
    port: 8000

frigate:
  server: http://192.168.20.10:5000
#  ignoressl: false
  public_url: https://[my-url]
#  headers:
  startup_check:
    attempts: 3
    interval: 30

  webapi:
    enabled: true
    interval: 10

  mqtt:
    enabled: false
#    server:
#    port:
#    clientid:
#    username:
#    password:
#    topic_prefix:

#  cameras:
#    exclude:
#      - test_cam_01

alerts:
  general:
    title: Frigate Alert
    timeformat: Mon, 02 Jan 2006 15:04:05 MST
    nosnap: allow
    snap_bbox: false
    snap_timestamp: false
    snap_crop: false
    max_snap_retry: 10
    notify_once: true
    notify_detections: false
    recheck_delay: 0
    audio_only: allow

#  quiet:
#    start:
#    end:

  zones:
    unzoned: allow
#    allow:
#     - test_zone_01
#    block:
#     - test_zone_02

  labels:
    min_score: 0
#    allow:
#     - person
#     - dog
#    block:
#     - bird

#  sublabels:
#    allow:
#     - ABCD
#    block:
#     - EFGH

  discord:
    enabled: false
#    webhook:
#    template:

  gotify:
    enabled: false
#    server:
#    token:
#    ignoressl:
#    template:

  mattermost:
    enabled: false
#    webhook:
#    channel:
#    username:
#    priority:
#    ignoressl:
#    headers:
#    template:

  ntfy:
    enabled: true
    server: https://[my-ntfy-url] # have also tried http://[my-ntfy-ip-address]
    topic: frigate
#    ignoressl: true
#    headers:
#    template:

  pushover:
    enabled: false
#    token:
#    userkey:
#    devices:
#    sound:
#    priority:
#    retry:
#    expire:
#    ttl:
#    template:

  signal:
    enabled: false
#    server:
#    account:
#    recipients:
#    ignoressl:
#    template:

  smtp:
    enabled: false
#    server:
#    port:
#    tls:
#    user:
#    password:
#    recipient:
#    template:

  telegram:
    enabled: false
#    chatid:
#    token:
#    template:

  webhook:
    enabled: false
#    server:
#    ignoressl:
#    method:
#    params:
#    headers:
#    template:


monitor:
  enabled: false
#  url:
#  interval:
#  ignoressl:
```

**Comment by freefd** [comment]
Hi @al70023,

You have disabled MQTT server in the configuration:
```yaml
  mqtt:
    enabled: false
```
At the same time, you said for the Ntfy server to use MQTT with topic called `frigate`:
```yaml
  ntfy:
    ...
    topic: frigate
```

To make the error message clearer, please enable `trace` log level: https://frigate-notify.0x2142.com/latest/config/options/
