### ISSUE TITLE
Webhook slightly malformed URL

### ISSUE THREAD

**Issue by DPattee** [0x2142/frigate-notify#267]
While working through using the webhook to trigger Synology Surveillance Station alerts, I noticed a minor issue in the url being generated.

```
webhook:  
    enabled: true
    server: foo.bar/webapi/SurveillanceStation/Webhook/Incoming/v1
    ignoressl:
    method: get
    params:
      token: aSDas
      text1: foo
```

results in log lines:

2025/05/11 15:09:58 -0700 WRN Unable to send alert error="Get \"foo.bar/webapi/SurveillanceStation/Webhook/Incoming/v1?&token=aSDas&text1=foo\": unsupported protocol scheme \"\"" event_id=1747001382.705843-8humpl provider=Webhook provider_id=0

(ignore the missing http:// in the server name, after adding that back in the error messages stopped appearing in the logs)

What we see is each element in the query string is preceeded by an "&" when generally the first element just appears directly after the "?" with no "&"

I don't think this is causing any problems, just something I noticed while debugging.
