### ISSUE TITLE
[FEATURE] get notification when camera goes offline

### ISSUE THREAD

**Issue by LeoSpyke** [0x2142/frigate-notify#287]
**Is your feature request related to a problem? Please describe.**
It would be useful to add monitoring of network reachability of cameras streams from the Frigate's POV.

In a real-world security scenario, such as a home intrusion, an attacker may intentionally disable or destroy IP cameras before proceeding further. If the monitoring software does not alert users when a camera stops responding, we might remain unaware that surveillance has been compromised until it’s too late.

**Describe the solution you'd like**
Please consider implementing a notification when a camera:
- goes offline unexpectedly (e.g., the streaming fps drop to 0)
- becomes unresponsive for a certain configurable period of time (e.g., customizable heartbeat timeout)
- do not recover after a specific number of retries

**Describe alternatives you've considered**
Custom ad-hoc scripts, but I'd rather prefer to stick with an AIO monitoring solution.

**Additional context**
Add a new **backwards compatible** config section under `general` like:
```yaml
alerts:  
  general:
    title:
    timeformat:
    nosnap:
    snap_bbox:
    snap_timestamp:
    [...]

  # === NEW SECTION === #
  cameras_check: # optional
    enabled: true # defaults to false
    period: X # global, how often (in seconds) to perform the probe
    threshold: Y # global, consecutive failures to consider the cam offline
    override: # specific cam params
      - name: cam-kitchen
        period: 3
        threshold: 3
      - name: cam-roof
        period: 10
        threshold: 7 # old shitty cam that goes offline frequently
    exclude: # mutually exclusive with "include"
      - cam-doghouse
      - cam-garage
    include: # mutually exclusive with "exclude"
      - cam-most-important
```
If a specified cam does not exists, just raise a warning in the logs and ignore it until the next service restart.
