### ISSUE TITLE
Cannot reach Frigate server

### ISSUE THREAD

**Issue by Man16** [0x2142/frigate-notify#293]
Hi

Struggling to make my notify instance connect to my Frigate instance

My docker compose file:

```
services:
  frigate-notify:
    image: ghcr.io/0x2142/frigate-notify:latest
    # Uncomment below if REST API server is enabled
    # ports:
    #   - "8000:8000"
    environment:
      - TZ=Europe/London
      - FN_LOGLEVEL=trace
    volumes:
      - ./config.yml:/app/config.yml
    restart: unless-stopped
```

My config.yml file:

```
app:
  mode: events
  api:
    enabled:
    port:

frigate:
  server: https://192.168.51.52:8971
  ignoressl: true
  username: redacted
  password: redacted

  mqtt:
    enabled: true
    server: 192.168.51.52
    # port:
    # clientid:
    username: redacted
    password: redacted
    # topic_prefix: 

alerts: 
  general:
    # title:
    # timeformat:
    # nosnap:
    # snap_bbox:
    # snap_timestamp:
    # snap_crop:
    # snap_hires:
    # max_snap_retry:
    # notify_once:
    notify_detections: true
    # recheck_delay:
    audio_only: drop

  # quiet:
    # start:
    # end:

  # zones:
    # unzoned: allow
    # allow:
    #  - test_zone_01
    # block:
    #  - test_zone_02

  # labels:
    # min_score:
    # allow:
    #  - person
    #  - dog
    # block:
    #  - bird

  # sublabels:
  #   allow:
  #    - ABCD
  #   block:
  #    - EFGH

  # license_plate:
    # enabled: false
    # allow:
    # block:

  discord:
    enabled: true
    webhook: redacted
    # disable_embed:
    # template:

monitor:
  enabled: true
  url: redacted
  interval: 15
  ignoressl: false

```

Log file from the frigate-notify container:

```
frigate-notify-1  | 2025/06/30 12:34:43 +0100 DBG config/validate.go:17 > Starting config validation...
frigate-notify-1  | 2025/06/30 12:34:43 +0100 DBG config/validate.go:311 > Frigate authentication: enabled
frigate-notify-1  | 2025/06/30 12:34:43 +0100 DBG config/validate.go:323 > Checking connection to Frigate server...
frigate-notify-1  | 2025/06/30 12:34:43 +0100 TRC util/frigate.go:49 > Checking Frigate auth token...
frigate-notify-1  | 2025/06/30 12:34:43 +0100 TRC util/httpclient.go:96 > HTTP GET headers=null insecure=true url=https://192.168.51.52:8971/api/profile
frigate-notify-1  | 2025/06/30 12:34:53 +0100 TRC util/frigate.go:52 > Frigate auth token expired or not obtained yet
frigate-notify-1  | 2025/06/30 12:34:53 +0100 DBG util/frigate.go:63 > Authenticating to Frigate...
frigate-notify-1  | 2025/06/30 12:34:53 +0100 TRC util/frigate.go:81 > Attempting authentication insecure=true url=https://192.168.51.52:8971/api/login
frigate-notify-1  | 2025/06/30 12:35:03 +0100 WRN config/validate.go:335 > Cannot reach Frigate server at https://192.168.51.52:8971 error="Post \"https://192.168.51.52:8971/api/login\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" attempt=1 interval=30 max_tries=5
frigate-notify-1  | 2025/06/30 12:35:33 +0100 TRC util/frigate.go:49 > Checking Frigate auth token...
frigate-notify-1  | 2025/06/30 12:35:33 +0100 TRC util/httpclient.go:96 > HTTP GET headers=null insecure=true url=https://192.168.51.52:8971/api/profile


frigate-notify-1  | 2025/06/30 12:35:43 +0100 TRC util/frigate.go:52 > Frigate auth token expired or not obtained yet
frigate-notify-1  | 2025/06/30 12:35:43 +0100 DBG util/frigate.go:63 > Authenticating to Frigate...
frigate-notify-1  | 2025/06/30 12:35:43 +0100 TRC util/frigate.go:81 > Attempting authentication insecure=true url=https://192.168.51.52:8971/api/login
frigate-notify-1  | 2025/06/30 12:35:53 +0100 WRN config/validate.go:335 > Cannot reach Frigate server at https://192.168.51.52:8971 error="Post \"https://192.168.51.52:8971/api/login\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" attempt=2 interval=30 max_tries=5

```
