### ISSUE TITLE
Feature: Support for Labels to allow/block sending notification

### ISSUE THREAD

**Issue by keezppc** [0x2142/frigate-notify#40]
It would be great if labels could be used to allow/block notifications like zones.  Something like:

```
alerts:
  labels:
    allow:
     - person
    block:
     - dog
```

Love this implementation, so nice to see easier notifications outside of Home Assistant
