### ISSUE TITLE
Feature: Multiple consumers for a single "Alerts" notifier

### ISSUE THREAD

**Issue by freefd** [0x2142/frigate-notify#43]
Sometimes it is necessary to make a broadcast message about the happened event to multiple consumers.
Not to break the top-level implementation and keep the base validations, below is a suggestion on how to augment the model by introducing a list to each of the notifier:
```yaml
...
alerts:
  telegram:
  - enabled: true
    chatid: 123456789
    token: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11
  - enabled: true
    chatid: 987654321
    token: 654321:CBA-FED4321ghIkl-zyx57W2v1u123ew11
  - enabled: true
    chatid: ...
    token: ...
  gotify:
  - enabled: true
    server: gotify.alpha.domain.tld
    token: ABCDEF
    ignoressl: true
  - enabled: true
    server: gotify.beta.domain.tld
    token: CABFED
    ignoressl: true
...
```
For existing frigate-notify users, backward compatibility with current behavior (single-key approach) can also be kept.

Currently, a workaround to support multiple notifier consumers of the same kind is to run several instances of frigate-notify with different MQTT `clientid` in the configuration.

Thank you.
