### ISSUE TITLE
Add Documentation on Debugging, how to bypass Zone already Alerted and configure its timeout

### ISSUE THREAD

**Issue by sn3ak** [0x2142/frigate-notify#61]
First, let me say thank you for creating this. While I am a HA user, I don't want frigate integrated to HA for reasons.  This is something that was sorely missing from frigate and I'm really happy that you created and shared this.

 Please add documentation on how to debug this.
Is there a log file that can be accessed somewhere?

as a newb, I setup everything (config below), and when I got home expected to get notified that a person was detected. I got nothing. I used docker compose attach to see the log files, but the only thing I can see is:
```
2024/05/16 01:56:15 Event ID 1715824522.190759-8cy0nu - Camera LivingRoom detected person in zone(s): []
2024/05/16 01:56:15 Event ID 1715824522.190759-8cy0nu - Start time: 2024-05-16 01:55:22 +0000 UTC
2024/05/16 01:56:15 Event ID 1715824522.190759-8cy0nu - Zone already alerted, skipping...
```

Figuring I set things up wrong, I changed the config file. Noticed there was a new release, pulled and started the container
Once again, I get a screen filled with `Zone already alerted, skipping...`.

I don't see any configuration to change the duration of an alerted zone. How long does it take to reset? How can I change it to be shorter? How can I reset the zone so I can hopefully see what's wrong and why the alerts didn't go out?

```
frigate:
  server: nope:5000
  ignoressl: true

  webapi:
    enabled: false
    interval: 30

  mqtt:
    enabled: true
    server: nope
    username: nope
    password: nope

  alerts:
    general:
      timeformat: Mon, 02 Jan 2006 15:04:05 PST
    labels:
      allow:
        - person
    zones:
      unzoned: allow

    pushover:
      enabled: true
      token: nope
      userkey: nope

    smtp:
      enabled: true
      server: mail.nope.net
      port: 587
      tls: true
      user: nope@nope.net
      password: nope
      recipient: me@nope.net
```

**Comment by sn3ak** [comment]
alright, I've figured out my own way to try and troubleshoot this by using docker compose run -lt and then stopping and starting the frigate container. that forces it to generate a new event.

I still can't make alerts work though. I stripped out a lot of the config and still no joy.

```
frigate:
  server: http://nope:5000
  ignoressl: true
  mqtt:
    enabled: true
    server: nope
    username: nope
    password: nope
  alerts:
    pushover:
      enabled: true
      token: nope
      userkey: nope
```

I've ran the test with the same yaml in this comment, but removed all of pushover: and put in the smtp: block from above.
