### ISSUE TITLE
Reduce logging or introduce debug log option

### ISSUE THREAD

**Issue by mike2307** [0x2142/frigate-notify#62]
At the moment two log messages are created at every polling occurrence.
Those look like:
```
2024/05/16 20:46:06 Checking for new events...
2024/05/16 20:46:06 Found 0 new events.
```

When using podman the default logging driver is journald. 
The used log priority/level is 3 (which appears as a warning) for whatever reason.

**In cases where the polling worked fine and there were no new events, the logging could be avoided completely.**
This would prevent the logs from getting flooded and only the messages of interest would go towards the log.
A **configuration option for debug logging** could be added in addition for some special use cases.

In my case I used a workaround to direct the logs into a "k8s" file instead using journald:
```
    logging:
      driver: k8s-file
      options:
        path: /opt/frigate/notify.log
        max-size: 10mb
```
