### ISSUE TITLE
ntfy button is local URL instead of public url

### ISSUE THREAD

**Issue by mabed-fr** [0x2142/frigate-notify#79]
Hello,

Thank for the work !

I have find a "problem"

In ntfy notification this button is local URL

![image](https://github.com/0x2142/frigate-notify/assets/25350431/ab2903b2-c3d7-4cc3-af71-774b27eafd34)

Is this normal behavior?

```yaml
frigate:
  # Frigate host URL (ex. https://frigate.yourdomain.tld)
  # This is required for both collection methods
  server: http://192.168.1.254:5000
  # Set to true if using SSL & a self-signed certificate
  ignoressl: true
  # Public / internet-facing Frigate URL, if different from above server address
  public_url: https://nvr**********.test.fr
  ```

  Regards
