### ISSUE TITLE
Help me get a proper notification

### ISSUE THREAD

**Issue by RebeliusGaming** [0x2142/frigate-notify#99]
Hello. 
First of all, thank you for developing this tool. Even someone as me managed to configure it.

I created my config.yml to send notifications to telegram, but instead of recieveing them as you show in the readme, I only get a simple line text.
How can I configure it to send me the Snapshot and also the links to view the camera or the clip?

I commented an [open issue](https://github.com/0x2142/frigate-notify/issues/98) asking to be able to directly attach the video in the telegram message. It would be awesome, but meanwhile, can you help me ?

```
frigate:
  server: httXXXXXXXXXXX3:5000/
  ignoressl: false
  public_url: httX.XXXXXXXXXX.ud
  headers: 
  startup_check:
    attempts: 5
    interval: 30

  webapi:
    enabled: true
    interval: 

  mqtt: 
    enabled: false
    server: 
    port:
    clientid:
    username: 
    password: 
    topic_prefix: 

  cameras:
    exclude:
  
alerts:  
  general:
    title: Alerta Alarma
    timeformat: Mon, 02 Jan 2006 15:04:05 MST
    nosnap:

  zones:
    unzoned: allow
    allow:
     - zone_0
     - zone_1
    block:

  labels:
    allow:
     - person
     - dog
    block:
     - bird

  discord:
    enabled: false
    webhook: 
    template:

  gotify:
    enabled: false
    server:
    token: 
    ignoressl:
    template:

  smtp:
    enabled: false
    server: 
    port: 
    tls: 
    user:
    password:
    recipient:
    template:

  telegram:
    enabled: true
    chatid: 2XXXXXXXXXXXXXXXX
    token: 73XXXXXXXXXXXXXXXXXXXXXXXXXQZHiFtYI
    template: Detección en {{ .Camera }}. Parece {{ .Label }}!! 

  pushover:
    enabled: false
    token:
    userkey:
    devices:
    priority:
    retry:
    expire:
    ttl:
    template:

  ntfy:
    enabled: false
    server:
    topic:
    ignoressl:
    headers:
    template:

  webhook:
    enabled: false
    server: 
    ignoressl:
    headers:
    template:

monitor:
  enabled: false
  url: 
  interval: 
  ignoressl:
```
